export const DISC={D:'Dominancia',I:'Influencia',S:'Estabilidad',C:'Cumplimiento'};
export const LABELS=['Nunca','Rara vez','A veces','Frecuentemente','Siempre'];
export const COMP=['Comunicación','Liderazgo','Toma de decisiones','Trabajo bajo presión','Trabajo en equipo','Adaptabilidad','Manejo de conflictos','Delegación','Orientación a resultados','Desarrollo de personas'];
const selfTexts=[
'Avanzo con decisión cuando debo alcanzar un objetivo exigente.','Genero conversación y entusiasmo en el equipo.','Escucho a las personas antes de cerrar una decisión.','Reviso datos y antecedentes antes de decidir.','Tomo decisiones oportunas aun con información incompleta.','Movilizo a otras personas hacia una meta común.','Dedico tiempo a apoyar el aprendizaje del equipo.','Cuido la calidad y consistencia del trabajo.','Priorizo rápidamente cuando surge una urgencia.','Genero espacios para que el equipo aporte ideas.','Escucho distintas posiciones antes de intervenir en un conflicto.','Entrego instrucciones claras, ordenadas y verificables.','Delego responsabilidades definiendo resultados y autonomía.','Me adapto con facilidad cuando cambian las prioridades.','Ajusto mi comunicación para cuidar la relación con el equipo.','Bajo presión, sigo revisando aspectos críticos para evitar errores.','Asumo la conducción cuando se necesita una dirección clara.','Reconozco los aportes positivos de las personas.','Confío tareas a otras personas y sigo disponible para apoyarlas.','Comprendo el nuevo estándar antes de aplicar un cambio.','Abordo los desacuerdos directamente cuando afectan el desempeño.','Expreso mis ideas con energía y claridad.','Mantengo serenidad cuando el entorno se vuelve tenso.','Comparo alternativas y consecuencias antes de una decisión crítica.','Establezco metas claras y hago seguimiento al avance.','Genero optimismo y disposición a colaborar en momentos de cambio.','Busco acuerdos para sostener el trabajo conjunto.','Al delegar, especifico criterios, responsabilidades y estándares.','Frente a cambios inesperados paso rápidamente a un nuevo plan.','Facilito conversaciones constructivas para reducir tensiones.','Entrego retroalimentación respetuosa y útil.','Estructuro la información en pasos comprensibles.','Asumo responsabilidad por las decisiones que tomo como líder.','Mantengo motivado al equipo en esfuerzos sostenidos.','Lidero generando confianza, consistencia y cercanía.','Mantengo estándares de trabajo aun cuando aumenta la presión.','Evito concentrar todas las decisiones operativas en mí.','Involucro a las personas cuando se implementan cambios.','Evito reaccionar impulsivamente ante desacuerdos.','Uso ejemplos concretos al entregar feedback.','Puedo priorizar y actuar ante múltiples demandas.','Confirmo que mi mensaje haya sido comprendido.','Me preocupo por la coordinación del equipo, no solo por mi tarea.','Uso indicadores o evidencias para verificar objetivos.','Establezco límites y expectativas claras cuando es necesario.','Me interesa conocer qué motiva y necesita cada integrante.','Doy espacio para que las personas resuelvan dentro de límites claros.','Ajusto métodos de trabajo cuando la evidencia muestra que deben mejorar.'
];
const discs=['D','I','S','C'];
const comps=['Orientación a resultados','Comunicación','Trabajo en equipo','Toma de decisiones','Toma de decisiones','Liderazgo','Desarrollo de personas','Orientación a resultados','Trabajo bajo presión','Trabajo en equipo','Manejo de conflictos','Comunicación','Delegación','Adaptabilidad','Comunicación','Trabajo bajo presión','Liderazgo','Desarrollo de personas','Delegación','Adaptabilidad','Manejo de conflictos','Comunicación','Trabajo bajo presión','Toma de decisiones','Orientación a resultados','Liderazgo','Trabajo en equipo','Delegación','Adaptabilidad','Manejo de conflictos','Desarrollo de personas','Comunicación','Toma de decisiones','Orientación a resultados','Liderazgo','Trabajo bajo presión','Delegación','Adaptabilidad','Manejo de conflictos','Desarrollo de personas','Trabajo bajo presión','Comunicación','Trabajo en equipo','Orientación a resultados','Liderazgo','Desarrollo de personas','Delegación','Adaptabilidad'];
export const SELF=selfTexts.map((text,i)=>({id:i+1,text,disc:discs[i%4],competency:comps[i],reverse:false}));
const teamTexts=['Define prioridades claras y mantiene foco en resultados.','Toma decisiones oportunas cuando la situación lo requiere.','Mantiene el foco y ordena prioridades bajo presión.','Entrega responsabilidades y autonomía con claridad.','Asume la conducción cuando se necesita dirección.','Aborda problemas que afectan al equipo.','Comunica sus ideas con claridad e involucra a las personas.','Motiva al equipo hacia objetivos comunes.','Promueve participación y considera los aportes del equipo.','Ayuda al equipo a involucrarse positivamente frente a cambios.','Reconoce los aportes y avances de las personas.','Favorece conversaciones constructivas ante tensiones.','Escucha antes de responder y considera otros puntos de vista.','Promueve un ambiente de cooperación y respeto.','Entrega apoyo y retroalimentación útil para mejorar.','Mantiene trato respetuoso y actitud estable en situaciones exigentes.','Confía en el equipo y permite resolver tareas dentro de límites claros.','Genera confianza y cercanía sin perder claridad en su rol.','Considera información y consecuencias antes de decisiones críticas.','Entrega instrucciones ordenadas, comprensibles y verificables.','Realiza seguimiento mediante evidencias, estándares o indicadores.','Mantiene estándares de seguridad y calidad incluso bajo presión.','Ajusta métodos de trabajo cuando existen antecedentes que justifican el cambio.','Al dar feedback utiliza ejemplos concretos y expectativas claras.'];
const teamComps=['Orientación a resultados','Toma de decisiones','Trabajo bajo presión','Delegación','Liderazgo','Manejo de conflictos','Comunicación','Liderazgo','Trabajo en equipo','Adaptabilidad','Desarrollo de personas','Manejo de conflictos','Comunicación','Trabajo en equipo','Desarrollo de personas','Trabajo bajo presión','Delegación','Liderazgo','Toma de decisiones','Comunicación','Orientación a resultados','Trabajo bajo presión','Adaptabilidad','Desarrollo de personas'];
export const TEAM=teamTexts.map((text,i)=>({id:i+1,text,disc:discs[i%4],competency:teamComps[i],reverse:false}));
